spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_db
    username: postgres
    password: senha
    driver-class-name: org.postgresql.Driver

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

  flyway:
    enabled: true
    baseline-on-migrate: false
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
